org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
flutter.impellerEnabled=false
android.useAndroidX=true
android.enableJetifier=true

# Unity export properties
unityStreamingAssets=
unity.androidSdkPath=/Applications/Unity/Hub/Editor/6000.4.4f1/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=/Applications/Unity/Hub/Editor/6000.4.4f1/PlaybackEngines/AndroidPlayer/NDK
